### ISSUE TITLE
Find a good name

### ISSUE THREAD

**Issue by flosse** [coop-care/org#1]
Current favorites:

- curama
- ecurama
- cocura

Subtitle:
- Software für selbstgeführte Pflegeorganisationen
- Software für Pflege auf Augenhöhe

Other ideas:

- Open Omaha - Cooperative Care Software
- Omaha Open Care
- OCC - open cooperative care
- CoOmaha / cOmaha - cooperative omaha
- Open CoCare
- coMahaCare / omahaCare
- open Care / oCare
- careish / carezy / careify
- ecocare
- sustaincare
- oma cura / omacura / open cura

The term "cooperative care" might be problematic.
Here are some sites/organizations you'll find:

- https://www.cooperativecare.org/
- http://coopcare.org/
- http://coopcarecmc.com/
- http://www.cooperativecare.us/

**Comment by flosse** [comment]
Do you have any ideas?

- open omaha
- OCC - open cooperative care

**Comment by flosse** [comment]
btw: there is a software called omaha: https://github.com/google/omaha

**Comment by michaelkamphausen** [comment]
I recognize that I begin liking "open omaha" (alliteration 👍) in combination with a localized, explanatory subtitle, like "Open Omaha – Cooperative Care Software" and "Open Omaha – Kooperative Pflege-Software"

**Comment by flosse** [comment]
- https://www.curasoft.de/
- https://www.curasoft.nl/
